- hosts: logstash
  become: yes

  ### This play will fail because the logstash host is in a private subnet.
#      The inventory needs to be configured with a ProxyCommand or jump host
#      setting to connect via the bastion.

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jre-headless
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Java (RedHat)
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Logstash
    ### This shell command is not idempotent. It's better to use
#              dedicated Ansible modules like 'apt_key', 'apt_repository',
#              and 'apt' for a more robust and reliable installation(avoid potential issues).
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        sudo apt-get install apt-transport-https -y
        echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
        sudo apt-get update && sudo apt-get install logstash -y
      when: ansible_os_family == 'Debian'

    - name: Ensure Logstash service is started and enabled
      service:
        name: logstash
        state: started
        enabled: yes